export const mockBuses = [
  {
    id: 1,
    number: 'RB-101',
    route: 'Route A',
    status: 'running',
    position: { x: 25, y: 30 },
    direction: 45,
    seatsAvailable: 12,
    totalSeats: 40,
    nextStop: 'Market Square',
    eta: '5 min',
    driver: 'Rajesh Kumar',
  },
  {
    id: 2,
    number: 'RB-102',
    route: 'Route B',
    status: 'running',
    position: { x: 60, y: 45 },
    direction: 135,
    seatsAvailable: 8,
    totalSeats: 40,
    nextStop: 'Central Station',
    eta: '3 min',
    driver: 'Amit Singh',
  },
  {
    id: 3,
    number: 'RB-103',
    route: 'Route C',
    status: 'delayed',
    position: { x: 40, y: 70 },
    direction: 270,
    seatsAvailable: 20,
    totalSeats: 40,
    nextStop: 'Village Center',
    eta: '12 min',
    driver: 'Suresh Patel',
  },
  {
    id: 4,
    number: 'RB-104',
    route: 'Route A',
    status: 'running',
    position: { x: 75, y: 25 },
    direction: 90,
    seatsAvailable: 5,
    totalSeats: 40,
    nextStop: 'Town Hall',
    eta: '7 min',
    driver: 'Vikram Sharma',
  },
];

export const mockRoutes = [
  {
    id: 1,
    name: 'Route A',
    from: 'Village North',
    to: 'City Center',
    distance: '45 km',
    fare: '₹50',
    frequency: 'Every 30 min',
    pathData: 'M 100 150 Q 200 100 400 200',
    stops: [
      { name: 'Village North', x: 20, y: 25 },
      { name: 'Market Square', x: 35, y: 35 },
      { name: 'Town Hall', x: 50, y: 40 },
      { name: 'Central Station', x: 65, y: 50 },
      { name: 'City Center', x: 80, y: 60 },
    ],
    schedule: [
      { departure: '06:00 AM', arrival: '07:30 AM', duration: '1h 30m' },
      { departure: '06:30 AM', arrival: '08:00 AM', duration: '1h 30m' },
      { departure: '07:00 AM', arrival: '08:30 AM', duration: '1h 30m' },
      { departure: '07:30 AM', arrival: '09:00 AM', duration: '1h 30m' },
      { departure: '08:00 AM', arrival: '09:30 AM', duration: '1h 30m' },
    ],
  },
  {
    id: 2,
    name: 'Route B',
    from: 'East Village',
    to: 'West Town',
    distance: '35 km',
    fare: '₹40',
    frequency: 'Every 45 min',
    pathData: 'M 400 100 Q 300 250 150 350',
    stops: [
      { name: 'East Village', x: 75, y: 20 },
      { name: 'River Bridge', x: 60, y: 30 },
      { name: 'Hill Station', x: 45, y: 50 },
      { name: 'Valley Stop', x: 30, y: 65 },
      { name: 'West Town', x: 15, y: 75 },
    ],
    schedule: [
      { departure: '06:15 AM', arrival: '07:30 AM', duration: '1h 15m' },
      { departure: '07:00 AM', arrival: '08:15 AM', duration: '1h 15m' },
      { departure: '07:45 AM', arrival: '09:00 AM', duration: '1h 15m' },
      { departure: '08:30 AM', arrival: '09:45 AM', duration: '1h 15m' },
    ],
  },
  {
    id: 3,
    name: 'Route C',
    from: 'South Point',
    to: 'North Plaza',
    distance: '52 km',
    fare: '₹60',
    frequency: 'Every hour',
    pathData: 'M 200 400 Q 250 250 300 100',
    stops: [
      { name: 'South Point', x: 25, y: 80 },
      { name: 'Village Center', x: 35, y: 65 },
      { name: 'Crossroads', x: 50, y: 50 },
      { name: 'Uptown', x: 65, y: 35 },
      { name: 'North Plaza', x: 80, y: 20 },
    ],
    schedule: [
      { departure: '06:00 AM', arrival: '07:45 AM', duration: '1h 45m' },
      { departure: '07:00 AM', arrival: '08:45 AM', duration: '1h 45m' },
      { departure: '08:00 AM', arrival: '09:45 AM', duration: '1h 45m' },
      { departure: '09:00 AM', arrival: '10:45 AM', duration: '1h 45m' },
    ],
  },
  {
    id: 4,
    name: 'Route D',
    from: 'Greenfield',
    to: 'Downtown',
    distance: '28 km',
    fare: '₹35',
    frequency: 'Every 20 min',
    pathData: 'M 150 200 L 350 300',
    stops: [
      { name: 'Greenfield', x: 30, y: 40 },
      { name: 'Farm Junction', x: 45, y: 45 },
      { name: 'Highway Stop', x: 60, y: 55 },
      { name: 'Downtown', x: 70, y: 65 },
    ],
    schedule: [
      { departure: '06:00 AM', arrival: '06:50 AM', duration: '50m' },
      { departure: '06:20 AM', arrival: '07:10 AM', duration: '50m' },
      { departure: '06:40 AM', arrival: '07:30 AM', duration: '50m' },
      { departure: '07:00 AM', arrival: '07:50 AM', duration: '50m' },
      { departure: '07:20 AM', arrival: '08:10 AM', duration: '50m' },
    ],
  },
];